////
////
//// This file is generated by the Pulse2Rust tool
////
////

pub fn minus(s1: (), s2: (), a1: &mut [i64], a2: &mut [i64], l: usize) -> () {
    let mut i = 0;
    while {
        let vi = i;
        vi < l
    } {
        let vi = i;
        let src = a2[vi];
        let dst = a1[vi];
        a1[vi] = src - dst;
        i = vi + 1;
    }
}
